version: '3.8'

services:
  frontend:
    build:
      context: ./front
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    build:
      context: ./backend
    environment:
      - ***REMOVED***
      - ***REMOVED***
      - ***REMOVED***
      - spring.rabbitmq.host=rabbitmq
      - ***REMOVED***
    ports:
      - '8080:8080'
    depends_on:
      - db
      - rabbitmq
    networks:
      - my-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Chmurowe2024!
      MYSQL_DATABASE: 38960054_pysznegloeats2
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
    driver: bridge
